export const DEFAULT_LENGTH = 10;
export const DEFAULT_START_Y = 10 * DEFAULT_LENGTH;

export const DEFAULT_PLAYGROUND_LENGTH = 10;
export const DEFAULT_PLAYGROUND_WIDTH = 10;
export const DEFAULT_PLAYGROUND_DEPTH = 8;